inherit_from: ../.rubocop.yml

Style/BlockDelimiters:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: [describe, context, it, fit, let, before]
